// packages/react-storybook/src/client/preview/error_display.js
import React from 'react';

const mainStyle = {
  position: 'fixed',
  top: 0,
  bottom: 0,
  left: 0,
  right: 0,
  padding: 20,
  backgroundColor: 'rgb(187, 49, 49)',
  color: '#FFF',
  WebkitFontSmoothing: 'antialiased'
};

const headingStyle = {
  fontSize: 20,
  fontWeight: 600,
  letterSpacing: 0.2,
  margin: '10px 0',
  fontFamily: `
    -apple-system, ".SFNSText-Regular", "San Francisco", Roboto, "Segoe UI",
    "Helvetica Neue", "Lucida Grande", sans-serif
    `
};

const codeStyle = {
  fontSize: 14,
  width: '100vw',
  overflow: 'auto'
};

const ErrorDisplay = ({ error }) => (
  <div style={mainStyle}>
    <div style={headingStyle}>{error.message}</div>
    <pre style={codeStyle}>
      <code>
        {error.stack}
      </code>
    </pre>
  </div>
);

ErrorDisplay.propTypes = {
  error: React.PropTypes.object.isRequired
};

export default ErrorDisplay;

// app/vue/src/client/preview/ErrorDisplay.vue
<template>
  <div class="main">
    <div class="heading">{{ message }}</div>
    <pre class="code">
      <code>
        {{ stack }}
      </code>
    </pre>
  </div>
</template>

<script>
  export default {
    name: 'error-display',
    props: {
      message: {
        type: String,
        required: true
      },
      stack: {
        type: String,
        required: true
      }
    }
  }
</script>

<style>
  .main {
    position: fixed;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    padding: 20;
    background-color: rgb(187, 49, 49);
    color: #FFF;
    webkit-font-smoothing: antialiased;
  }

  .heading {
    font-size: 20;
    font-weight: 600;
    letter-spacing: 0.2;
    margin: 10px 0;
    font-family: -apple-system, ".SFNSText-Regular", "San Francisco", Roboto, "Segoe UI", "Helvetica Neue", "Lucida Grande", sans-serif;
  }
  
  .code {
    font-size: 14;
    width: 100vw;
    overflow: auto;
  }
</style>
