// app/angular/src/demo/button.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'button-component',
  template: `
      <button>{{ text }}</button>
  `,
  styles: [
      `
        button {
          border: 1px solid #eee;
          border-radius: 3px;
          background-color: #FFFFFF;
          cursor: pointer;
          font-size: 15px;
          padding: 3px 10px;
          margin: 10px;
        }
      `
  ]
})
export default class ButtonComponent {
    @Input() text = '';
}

// lib/cli/generators/SVELTE/template/stories/button.svelte
<button class="button" on:click={onClick}>
    {text}
</button>

<style>
    .button {
      border: 1px solid #eee;
      border-radius: 3px;
      backgroundColor: #FFFFFF;
      cursor: pointer;
      font-size: 15px;
      padding: 3px 10px;
      margin: 10px;
    }
</style>

<script>
  import { createEventDispatcher } from 'svelte';
  
  export let text = '';

  const dispatch = createEventDispatcher();

  function onClick(event) {
    dispatch('click', event)
  }
</script>
