// examples/svelte-kitchen-sink/src/components/Button.svelte
<button
  class="button {roundedClass}"
  on:click="toggleRoundedClass(event)">
  <slot></slot>
</button>

<style>
  .rounded {
    border-radius: 5px;
  }

  .button {
    border: 3px solid;
    padding: 10px 20px;
    background-color: white;
    outline: none;
  }

</style>

<script>
  export default {
    data () {
      return {
        rounded: true
      };
    },

    computed: {
      roundedClass({ rounded }) {
        return rounded ? 'rounded' : ''
      }
    },

    methods: {
      toggleRoundedClass() {
        const {rounded} = this.get();

        this.set({rounded: !rounded});
      }
    }
  }
</script>

// examples/vue/src/stories/Button.vue
<template>
  <button class="button" :style="{color: color, borderColor: color}" @click="handleClick" :class="{rounded: rounded}"><slot></slot></button>
</template>

<script>
  export default {
    props: {
      rounded: Boolean,
      handleClick: {
        default: () => () => null
      },
      color: {
        default: '#42b983'
      }
    }
  }
</script>

<style>
  .button {
    border: 3px solid;
    padding: 10px 20px;
    border-radius: 3px;
    background-color: white;
    outline: none;
  }
</style>
